
language: node_js
node_js:
- "10"

script: echo "Running tests against $(node -v)..."

jobs:
  include:
  - stage: Produce Coverage
    node_js: node
    install: yarn install
    before_script: ls
    script: jest --coverage && cat ./coverage/lcov.info | coveralls && rm -rf ./coverage
